Update to work with the ETOS controller
eiffel-community/etos-environment-provider pull request #106
Opened 2024-07-26 12:06 UTC by t-persson

### Applicable Issues

eiffel-community/etos#242

### Description of the Change

Update the environment provider to work with the new ETOS kubernetes controller.
This change should still work with the current way of running ETOS and will only "activate" if the environment provider
detects that it is running as a part of a TestRun resource.

### Alternate Designs

I thought about implementing a separate package that could run independently from the current way, however I decided against this as it would require me to move way from the current implementation of the environment provider which is an implementation that works. I do not want this change to be a complete rewrite; we must piggy-back on the code that we are currently running.
I also thought about creating a docker container and running the provider as a part of the EnvironmentRequest resource, but that would also move away too far from the current implementation in ETOS. This is something that we should do in steps so that we do not break everything.

### Possible Drawbacks

I did increase the complexity of the environment provider. I outlined some reasons for this in the alternate designs part. This complexity should be removed when the PoC is finished. Either remove the etos controller parts or the current environment provider part.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Tobias Persson <tobias.persson@axis.com>

2024-08-20 09:48 UTC, andmat900 commented on src/iut_provider/utilities/prepare.py
> +                # dataset.add("config", self.config)
remove if not used

2024-08-20 09:48 UTC, andmat900 commented on src/execution_space_provider/utilities/external_provider.py
> +            "artifact_created": self.dataset.get("artifact_created") or {},
Are these fields allowed to be empty dictionaries? 
Is some additional validation needed here or anywhere else?

2024-08-20 09:48 UTC, andmat900 commented on src/environment_provider/lib/registry.py
> +            self.logger.error("Could not retrieve execution spce provider from database")
"spce" > "space"

2024-08-20 09:48 UTC, andmat900 commented on src/environment_provider/lib/config.py
> +    def requests(self) -> list[EnvironmentRequestSchema]:  # TODO: This shall not return a list
fix TODO, change name "requests" > "request" ?

2024-08-20 09:48 UTC, andmat900 commented on src/environment_provider/lib/config.py
> +        timeout = time.time() + (self.etos.config.get("EVENT_DATA_TIMEOUT") or 30)  # TODO: This default is nogood
Are the polls too frequent? Too much load? Use less frequent polling?

2024-08-20 09:48 UTC, andmat900 commented on Dockerfile
> +FROM python:3.11-bookworm AS build
migrate to 3.11 already?

2024-08-20 09:48 UTC, andmat900 commented on src/environment_provider/lib/config.py
> +                    maximumAmount=10,
should this be hard-coded?

2024-08-26 06:00 UTC, t-persson commented on src/execution_space_provider/utilities/external_provider.py
> +            "artifact_created": self.dataset.get("artifact_created") or {},
They are allowed to be empty and null. Validation is expected in the external provider, but it shall not fail if these are not set.

2024-08-26 06:01 UTC, t-persson commented on src/environment_provider/lib/config.py
> +    def requests(self) -> list[EnvironmentRequestSchema]:  # TODO: This shall not return a list
This is a temporary measure required because of how we are running the environment today. When the current way of running the environment provider is changed, this method shall be fixed.

2024-08-26 06:05 UTC, t-persson commented on src/environment_provider/lib/config.py
> +        timeout = time.time() + (self.etos.config.get("EVENT_DATA_TIMEOUT") or 30)  # TODO: This default is nogood
The default was never used since the default is set elsewhere. `or 30` was added because my editor screams at me that the config may return None. Fixed by ignoring the type.

2024-08-26 06:09 UTC, t-persson commented on src/environment_provider/lib/config.py
> +                    maximumAmount=10,
minimumAmount is correct, maximumAmount is currently unused. Added a TODO to clarify.

2024-08-26 06:12 UTC, t-persson commented on Dockerfile
> +FROM python:3.11-bookworm AS build
This is because of the feature `ExceptionGroup` that is being used in the `releaser.py`. This feature is not used when running the environment provider in the current way (where we use python3.9 as per the suite runner image).
This Dockerfile will only be used in the ETOS controller update.

2024-08-26 06:15 UTC, andmat900 commented on Dockerfile
> +FROM python:3.11-bookworm AS build
In cases where you have to explain, please add comments to the code.

2024-10-16 11:42 UTC, t-persson commented
Force push since I had to rebase

2024-10-22 08:34 UTC, t-persson commented on Dockerfile
> +FROM python:3.11-bookworm AS build
Went back to 3.9 due to ExceptionGroups not being worth it yet.

2024-11-20 14:35 UTC, andmat900 commented on src/environment_provider/lib/releaser.py
> +class Executor(Releaser):
ExecutorReleaser?

2024-11-20 14:35 UTC, andmat900 commented on src/environment_provider/lib/releaser.py
> +class LogArea(Releaser):
LogAreaReleaser?

2024-11-20 14:35 UTC, andmat900 commented on src/environment_provider/environment_provider.py
> +        labels["etos.eiffel-community.github.io/suite-id"] = sub_suite["test_suite_started_id"]
1. Is suite-id same as testrun-id, i. e. etos.eiffel-community.github.io/id=abc  ?
2. How will these objects be linked: testrun, suite id, subsuite id, environment id? Will it be possible to trace from environment id to testrun id?  Not sure, but one use case might be troubleshooting.

2024-11-21 08:59 UTC, fredjn requested changes

2024-11-21 09:05 UTC, t-persson commented on src/environment_provider/environment_provider.py
>              # TODO: Add link ref to docs that describe how the config is done.
This is an old TODO. We wanted to return a link reference to the user who started ETOS with information on how to configure, instead of just returning "Please do a proper configuration of EnvironmentProvider before requesting an environment." as that is not super-clear to anyone.

2024-11-21 09:06 UTC, t-persson commented on src/environment_provider/environment_provider.py
> +        self.tracer = opentelemetry.trace.get_tracer(__name__)  # type:ignore
`"trace" is not a known attribute of module "opentelemetry"` or so my editor says.

2024-11-21 09:07 UTC, t-persson commented on src/environment_provider/environment.py
> +    run(sys.argv[1])
This is to be able to run it as we do in the controller. We start a job that runs this script.

2024-11-21 09:19 UTC, t-persson commented on src/environment_provider/lib/graphql.py
> +          id
We don't need it, but it looked cleaner to do:

`artifact=artifact["meta"]["id"],`
instead of
`artifact=tercc["links"][0]["target"],`

Will change.

2024-11-21 09:27 UTC, t-persson commented on src/environment_provider/lib/config.py
> +                return batch
If a TERCC is sent without batches or batchesUri then we would not enter these if-statements at all and return an empty list (line 218).
The potential error does not get caught, but no environment will be created and the environment provider shuts down.

But it should also be noted that the environment provider would never be called by the suite runner if there are no test suites in the TERCC and this problem would not happen. This particular code is not run in the controller update only when running the environment provider as a part of the suite runner.

2024-11-21 09:33 UTC, t-persson commented on src/environment_provider/lib/config.py
> +        response = request_artifact_created(self.etos, tercc["links"][0]["target"])
True that it is possible to call this method with an empty dictionary, this would lead to a KeyError being raised which is caught by the `run` method in environment_provider.py and an error is returned stating that we could not create an environment for test (this is a user log as well).

However, as I noted in another comment, this would not happen since the ESR validates that the environment variable is set at start-up and this particular code is only executed when not running in the ETOS controller and the environment provider is executed as a part of the suite runner, meaning that the validation in ESR also validates it for the environment provider.
If the TERCC environment variable is an empty dictionary, then the ESR won't start the environment provider at all.

2024-11-21 09:36 UTC, t-persson commented on src/environment_provider/lib/config.py
> +        ), "Suite runner IDs must be provided when running outside of controller"
All exceptions are caught by the `run` method in environment_provider.py.
`run` -> `config.requests` -> `request_from_tercc`

The assertion was added mostly because my editor complained that the variable could be None (due to the type-hint at the top, when running in controller it is None).
This particular assertion should be considered a helper for us when we are verifying changes and it should (shall, won't) happen when our users are running ETOS.

2024-11-21 09:38 UTC, t-persson commented on src/environment_provider/lib/config.py
> +            testrun_id = self.requests[0].spec.identifier
Correct. Will clarify what "This" is.

2024-11-21 09:44 UTC, t-persson commented on src/environment_provider/environment_provider.py
> +        labels["etos.eiffel-community.github.io/suite-id"] = sub_suite["test_suite_started_id"]
testrun-id is the TERCC ID.
suite-id is the main TestSuiteStarted ID
sub-suite-id is the subsuite TestSuiteStarted ID

The Environment resource that is created here has the EnvironmentRequest as owner which has the `etos.eiffel-community.github.io/id"` set to the TestRun that created it. The EnvironmentRequest also has the TestRun as owner.

2024-11-21 09:50 UTC, t-persson commented on src/environment_provider/lib/releaser.py
> +class Iut(Releaser):
I disagree with this since it would stutter when reading it. `IutReleaser(Releaser)`
These "releasers" are only called in the `EnvironmentReleaser` class which makes the call `EnvironmentReleaser().run()`. Should be clear enough

2024-11-21 09:54 UTC, t-persson commented on src/environment_provider/environment_provider.py
> +            f"{os.getenv('ETOS_API')}/v1alpha/testrun/{environment_id}",
No checks, but I would rather write an issue to identify all these configuration variables in all of our services, document them and add checks for them.
This variable is, currently, set by the controller so I am not afraid that having this without a check will break in the near future.

Will write an issue when I'm done here.

2024-11-21 10:00 UTC, t-persson commented on src/environment_provider/lib/config.py
> +            testrun_id = self.requests[0].spec.identifier
Clarified, please review.

2024-11-21 10:20 UTC, fredjn commented on src/environment_provider/lib/config.py
> +                return batch
Ah true, my mistake. However the error message woudl be kind of confusing since it would indicate that bith Batches and BatchesUri was set when infact non of them were.

2024-11-21 10:32 UTC, fredjn commented on src/environment_provider/environment_provider.py
> +        self.tracer = opentelemetry.trace.get_tracer(__name__)  # type:ignore
I guess that could be from how we import it. I get similar problems. Although if we do `from opentelemetry import trace` that seems to help, at least in my case.

2024-11-21 10:55 UTC, fredjn approved these changes

2024-11-21 10:55 UTC, fredjn commented on src/environment_provider/lib/config.py
> +                return batch
True (again), my mind got stuck on  the default for 'data'.

2024-11-21 11:22 UTC, merged