Add logging support from etos library
eiffel-community/etos-environment-provider pull request #23
Opened 2021-01-13 12:09 UTC by t-persson

### Applicable Issues

eiffel-community/etos#70

### Description of the Change

Add logging support from etos library 1.8.0

### Alternate Designs

We should consider reducing the amount of logging done from separate tools.
Made it with all the logs in order to figure out what is needed.

### Benefits

The log output is now a rotating set of files that work well with filebeat and logstash.

### Possible Drawbacks

We might lock ourselves into filebeat and logstash.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Tobias Persson <tobias.persson@axis.com>

2021-01-13 12:23 UTC, andjoe-axis approved these changes
+1

2021-01-13 12:46 UTC, t-persson commented on src/environment_provider/__init__.py
> +setup_logging("ETOS Environment Provider", VERSION, "development")
the "development" text should be updated to "production" depending on the state of the software

2021-01-14 09:36 UTC, fredjn requested changes

2021-01-14 10:42 UTC, t-persson commented on Dockerfile.workers
> +RUN groupadd -r etos && useradd -r -m -s /bin/false -g etos etos
Explicit is better than implicit.

2021-01-14 10:43 UTC, t-persson commented on src/environment_provider/__init__.py
> +# Copyright 2020-2021 Axis Communications AB.
Because those are the rules of Eiffel community

https://github.com/eiffel-community/.github/blob/master/CONTRIBUTING.md#license-management

2021-01-14 10:59 UTC, fredjn commented on Dockerfile.workers
> +RUN groupadd -r etos && useradd -r -m -s /bin/false -g etos etos
fair enough

2021-01-14 11:00 UTC, fredjn approved these changes

2021-01-14 11:15 UTC, merged