Fix broken prepare step in Environment Provider
eiffel-community/etos-environment-provider pull request #28
Opened 2021-03-02 14:44 UTC by fredjn

### Applicable Issues
Fixes eiffel-community/etos#77

### Description of the Change

- Re-allocated memory for checked out IUT data, that is passed by ref.
- Fixed bug calculation of which IUTs to check-in when prepare step is completed
- Unrelated update to .gitignore

### Alternate Designs
None

### Benefits
A working prepare step with proper check-out and check-in of OUTs

### Possible Drawbacks
None

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Fredrik Fristedt \<fredrik.fristedt@axis.com\>

2021-03-02 19:33 UTC, t-persson requested changes
Don't forget to update the copyright year

2021-03-02 19:33 UTC, t-persson commented on src/environment_provider/iut/iut_provider.py
> +
This change should not be necessary now that we deepcopy the iuts

2021-03-02 19:33 UTC, t-persson commented on src/environment_provider/iut/prepare.py
> +        iuts = deepcopy(iuts)
There is another deepcopy below this line. Is that one still necessary?

2021-03-02 19:35 UTC, t-persson commented on src/environment_provider/iut/prepare.py
> +        iuts = deepcopy(iuts)
Yes it is. Since that one is for the dataset

2021-03-03 07:22 UTC, fredjn commented on src/environment_provider/iut/iut_provider.py
> +
Prepared iuts can still come back empty.

2021-03-03 07:28 UTC, fredjn commented on src/environment_provider/iut/iut_provider.py
> +
True

2021-03-03 08:31 UTC, andjoe-axis approved these changes

2021-03-03 10:51 UTC, t-persson approved these changes

2021-03-03 10:51 UTC, merged