Check in single environment
eiffel-community/etos-environment-provider pull request #63
Opened 2022-08-01 08:39 UTC by t-persson

### Applicable Issues

eiffel-community/etos-suite-runner#25

### Description of the Change

Added the ability to both check-in a single environment as well as a full environment (the previous behavior).

### Alternate Designs

We could remove the full check-in, but it is nice to have as a fall-back. There's now a lot of database code in the webserver that I don't really like but will do for now.

### Benefits

This will allow us to have execution spaces, log areas and IUTs become available as each test suite has finished. It can also be considered a pre-cursor to sequential execution.

### Possible Drawbacks

Complexity

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Tobias Persson <tobias.persson@axis.com>

2022-08-22 11:09 UTC, fredjn requested changes
Perhaps add test for release_single.

2022-08-22 11:09 UTC, fredjn commented on src/environment_provider_api/webserver.py
>                  "Missing parameters", "'id' or 'release' are required parameters."
Add 'single_release' paramter.

2022-08-25 08:23 UTC, andjoe-axis approved these changes

2022-08-26 10:05 UTC, t-persson commented
> Perhaps add test for release_single.

We don't have any tests for the webserver single_release (nor release). I think this is because it's harder to do these "real" tests within the webserver part. Doing a full release does utilize the code for single release, so I am not afraid of this part just breaking though since we test full release.

2022-08-26 10:06 UTC, fredjn approved these changes

2022-08-26 10:09 UTC, merged