User logs
eiffel-community/etos-environment-provider pull request #73
Opened 2023-08-14 12:58 UTC by t-persson

### Applicable Issues

#eiffel-community/etos#148

### Description of the Change

Send user logs to RabbitMQ for the ETOS client.
Also had to update a few packages for this to work so I updated everything.

### Alternate Designs

I went for the least amount of logging that I felt gave something. There might still be some messages that can be added, but for now I just wanted to add support for it and send something. This makes it easier to update which messages to send in the future.

### Benefits

This will give some information on the goings-on inside of the environment provider for our clients.

### Possible Drawbacks

Nothing really.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Tobias Persson <tobias.persson@axis.com>

2023-08-16 10:55 UTC, fredjn requested changes

2023-08-16 10:55 UTC, fredjn commented on src/environment_provider/environment_provider.py
> +        self.logger.info(
It would make more sense to log the information about the timeout last (E.g. after "checking out iut/exec space/log area). To be even more friendly we could put the time and date of the timeout expiration.

2023-08-16 10:55 UTC, fredjn commented on src/environment_provider/environment_provider.py
Adding a few newlines in this file would make it a bit more readable IMO.

2023-08-18 07:03 UTC, t-persson commented on src/environment_provider/environment_provider.py
Done

2023-08-18 07:04 UTC, t-persson commented on src/environment_provider/environment_provider.py
> +        self.logger.info(
Looking into a good format. Current suggestion is: `Timeout for checkout at: 2023-08-18 07:57:41 (0h 0m 40s)`

2023-08-18 12:52 UTC, merged