Updated to use ETCD database instead of redis
eiffel-community/etos-environment-provider pull request #85
Opened 2024-01-10 10:50 UTC by t-persson

### Applicable Issues

eiffel-community/etos#205

### Description of the Change

Start using the ETCD database instead of redis.
Also cleaned up a few deprecated things.
Removed the SubSuite endpoint since it's no longer used. Added type-hints to everything.
Removed copyright year from all files.

### Alternate Designs

We could've set up the ETCDPath as a database instead of using it as a path-ish object. I really did enjoy using the path-ish object since it really represents the representation in ETCD.
I added a few compatibility layers in the database, these could've been avoided but then I would've had to sync a change in the ESR at the same time which is prone to failures. Instead we should have the compatibility layers now and remove them when the ESR has been updated.
The ETCDPath object should also be added to the ETOS library. I wanted to use the object "for real" before making big changes to the library though, so moving it should be done in the future.

### Benefits

We are now using a database that's intended as a database and we have now put more thought into the structure of the database. Something that we did not have when the redis-hack was implemented.

### Possible Drawbacks

We are now running both redis and etcd in the cluster for a single service. We are looking into moving over from python to golang and that change may remove the need for redis since it's used by celery.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Tobias Persson <tobias.persson@axis.com>

2024-01-11 07:24 UTC, t-persson commented on src/environment_provider_api/backend/environment.py
> +    registry.testrun.delete_all()
This `delete_all` should be done by the ESR, just before shutting down.

2024-01-17 09:40 UTC, fredjn requested changes

2024-01-22 06:50 UTC, t-persson commented on src/environment_provider_api/backend/environment.py
> +    for suite, metadata in registry.testrun.join("suite").read_all():
Falcon will return a server error which, in my opinion, is correct since we are reading from the database and not receiving the problematic values from the user.

2024-01-22 06:54 UTC, t-persson commented on src/environment_provider_api/backend/environment.py
> +def request_environment(suite_id: str, suite_runner_ids: list[str]) -> str:
Yes. It's the ID of the task started by celery.

2024-01-22 06:56 UTC, t-persson commented on src/environment_provider/lib/config.py
> +    def identity(self) -> str:
Nope. We return `.to_string()`

2024-02-05 13:51 UTC, fredjn commented on src/environment_provider/lib/config.py
> +    def identity(self) -> str:
Nope. We return `.from_string()`

2024-02-05 14:01 UTC, fredjn approved these changes

2024-02-07 07:54 UTC, merged