Remove provider registration and configuration
eiffel-community/etos-environment-provider pull request #95
Opened 2024-03-26 10:40 UTC by andmat900

### Applicable Issues

https://github.com/eiffel-community/etos/issues/227

### Description of the Change

This change removes old unused code. Environment registration and configuration has been recently implemented in etos-api.

### Alternate Designs

### Possible Drawbacks

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Andrei Matveyeu, andrei.matveyeu@axis.com

2024-03-26 12:49 UTC, t-persson requested changes

2024-03-26 12:49 UTC, t-persson commented on src/environment_provider/environment.py
> +    return request.get_param("single_release")
These should probably be removed as well since we've removed the API (and they require the request object from falcon, which we get from the APIs)

2024-03-26 12:49 UTC, t-persson commented on src/environment_provider/environment.py
> +    return get_environment.delay(suite_id, suite_runner_ids).id
This should no longer be necessary since we are not using celery in the suite runner anymore.

2024-03-26 12:49 UTC, t-persson commented on src/environment_provider/environment.py
> +    return {"status": status, "result": result}
Should no longer be necessary since we are not using celery in the suite runner anymore

2024-03-26 12:49 UTC, t-persson commented on src/environment_provider/environment.py
> +def release_environment(
Since this function has moved to another namespace, we must update the suite runner.

2024-03-26 12:49 UTC, t-persson commented on src/environment_provider/environment.py
> +def release_full_environment(etos: ETOS, jsontas: JsonTas, suite_id: str) -> tuple[bool, str]:
Since this function has moved to another namespace, we must update the suite runner.

2024-03-26 12:49 UTC, t-persson commented on src/environment_provider_api/webserver.py
> -# Copyright Axis Communications AB.
Please update requirements and setup.cfg files accordingly. We are no longer using falcon or celery, right?

2024-03-27 10:25 UTC, andmat900 commented on src/environment_provider/environment.py
> +def release_environment(
Will create a pull request.

2024-03-27 10:25 UTC, andmat900 commented on src/environment_provider/environment.py
> +def release_full_environment(etos: ETOS, jsontas: JsonTas, suite_id: str) -> tuple[bool, str]:
Will create a pull request.

2024-03-27 10:53 UTC, andmat900 commented on src/environment_provider_api/webserver.py
> -# Copyright Axis Communications AB.
Removed falcon only. Celery code will be left as is for now.

2024-03-27 15:08 UTC, t-persson approved these changes

2024-03-28 07:09 UTC, merged