Add OpenTelemetry tracing
eiffel-community/etos-environment-provider pull request #96
Opened 2024-04-10 12:43 UTC by andmat900

### Applicable Issues

- https://github.com/eiffel-community/etos/issues/228
- Depends On https://github.com/eiffel-community/etos-library/pull/27

### Description of the Change

This change adds OpenTelemetry instrumentation to etos-environment-provider.

### Alternate Designs

### Possible Drawbacks

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Andrei Matveyeu, andrei.matveyeu@axis.com

2024-04-17 14:07 UTC, fredjn commented on src/environment_provider/environment_provider.py
> +        self.tracer_context = get_current_context()
I can't seem to find any usage of the `tracer_context`-variable, but I might have missed something?

2024-04-17 14:07 UTC, fredjn commented on src/environment_provider/environment_provider.py
> +        self.tracer_context = get_current_context()
This is also the only usage of `get_current_context` ?

2024-04-17 14:07 UTC, fredjn commented on src/iut_provider/utilities/external_provider.py
> +        if otel_span is not None:
Same as previous comments

2024-04-17 14:07 UTC, fredjn commented on src/log_area_provider/utilities/external_provider.py
> +        otel_span = opentelemetry.trace.get_current_span()
Same as previous comments

2024-04-17 14:07 UTC, fredjn commented on src/log_area_provider/utilities/external_provider.py
> +        if otel_span is not None:
Same as previous comments

2024-04-22 10:47 UTC, t-persson requested changes

2024-04-22 10:47 UTC, t-persson commented on src/environment_provider/environment.py
> +            failure = exception
We should record this exception:
https://opentelemetry-python.readthedocs.io/en/latest/api/trace.span.html#opentelemetry.trace.span.Span.record_exception

2024-04-22 10:47 UTC, t-persson commented on src/environment_provider/environment.py
> +            failure = exception
We should record this exception:
https://opentelemetry-python.readthedocs.io/en/latest/api/trace.span.html#opentelemetry.trace.span.Span.record_exception

2024-04-22 10:47 UTC, t-persson commented on src/environment_provider/environment.py
> +            failure = exception
We should record this exception:
https://opentelemetry-python.readthedocs.io/en/latest/api/trace.span.html#opentelemetry.trace.span.Span.record_exception

2024-04-22 10:47 UTC, t-persson commented on src/execution_space_provider/utilities/external_provider.py
> +            self.logger.info("OpenTelemetry context headers: %s", headers)
We don't use opentelemetry here

2024-04-22 10:47 UTC, t-persson commented on src/execution_space_provider/utilities/external_provider.py
> +        self.logger.info("OpenTelemetry context headers: %s", headers)
Nit: Necessary?

2024-04-22 10:47 UTC, t-persson commented on src/execution_space_provider/utilities/external_provider.py
> +        self.logger.info("OpenTelemetry context headers: %s", headers)
Nit: Necessary?

2024-04-22 10:47 UTC, t-persson commented on src/execution_space_provider/utilities/external_provider.py
> +        otel_span.set_attribute("request.body", json.dumps(execution_spaces, indent=4))
Should we really indent the JSON here? It makes the request to the OTEL collector larger.
This comment applies to all indent=4 dumps

2024-04-23 11:50 UTC, andmat900 commented on src/environment_provider/environment.py
> +            failure = exception
Done

2024-04-23 11:50 UTC, andmat900 commented on src/environment_provider/environment.py
> +            failure = exception
Done

2024-04-23 11:52 UTC, andmat900 commented on src/execution_space_provider/utilities/external_provider.py
> +        otel_span.set_attribute("request.body", json.dumps(execution_spaces, indent=4))
If this isn't done, the JSON is shown in Jaeger as a string without pretty formatting.

2024-04-23 11:52 UTC, andmat900 commented on src/environment_provider/environment.py
> +            failure = exception
Done

2024-04-30 09:03 UTC, fredjn commented on src/execution_space_provider/utilities/external_provider.py
> +        otel_span.set_attribute("request.body", json.dumps(execution_spaces, indent=4))
I'm leaning towards keeping the amount of data down, and If we feel it's a problem to re-format the json (when/if we inspect it) we can re-evaluate and refactor.

2024-04-30 09:17 UTC, fredjn approved these changes

2024-05-02 07:19 UTC, andmat900 commented on src/execution_space_provider/utilities/external_provider.py
> +        otel_span.set_attribute("request.body", json.dumps(execution_spaces, indent=4))
Pretty formatting is now removed.

2024-05-02 07:23 UTC, andmat900 commented on src/environment_provider/environment_provider.py
> +            with self.tracer.start_as_current_span("request_iuts") as span:
The latest update includes mandatory attributes. Note that it increases the amount of instrumentation code. A better way might be to encapsulate instrumentation somewhere else, like etos_library.

2024-05-02 08:10 UTC, fredjn commented on src/log_area_provider/utilities/external_provider.py
> +        otel_span.set_attribute(SpanAttributes.URL_FULL, host)
Perhaps rename to span to keep naming consistent?

2024-05-02 10:16 UTC, andmat900 commented on src/log_area_provider/utilities/external_provider.py
> +        otel_span.set_attribute(SpanAttributes.URL_FULL, host)
Changed the name.

2024-05-02 10:56 UTC, merged